 criaCartao('Célula', 'O que é uma célula?', 'A célula é a unidade estrutural e funcional básica de todos os seres vivos.'),
    criaCartao('Célula', 'Quais são os dois tipos básicos de células?', 'Procariontes e eucariontes.'),
    criaCartao('Célula', 'O que diferencia células procariontes de eucariontes?', 'As células procariontes não possuem núcleo delimitado por membrana, enquanto as eucariontes possuem.'),
    criaCartao('Célula', 'Qual é a função da membrana plasmática?', 'Controlar a entrada e saída de substâncias da célula.'),
    criaCartao('Célula', 'O que é citoplasma?', 'É a região da célula onde estão localizadas as organelas e outras estruturas celulares.'),
    criaCartao('Genética', 'O que é DNA?', 'O DNA é o material genético que contém as informações para o funcionamento e desenvolvimento dos organismos.'),
    criaCartao('Genética', 'Qual é a função do RNA?', 'O RNA é responsável por transmitir informações genéticas do DNA para a síntese de proteínas.'),
    criaCartao('Genética', 'O que são genes?', 'Genes são segmentos do DNA que contêm informações para a produção de proteínas.'),
    criaCartao('Genética', 'O que é um cromossomo?', 'É uma estrutura formada por DNA e proteínas que carrega os genes.'),
    criaCartao('Genética', 'O que é mutação genética?', 'É uma alteração na sequência de nucleotídeos do DNA.'),
    criaCartao('Botânica', 'O que é fotossíntese?', 'É o processo pelo qual as plantas transformam luz solar, água e dióxido de carbono em glicose e oxigênio.'),
    criaCartao('Botânica', 'Quais são os principais tipos de tecidos vegetais?', 'Meristemas, tecidos de revestimento, tecidos de condução e tecidos de sustentação.'),
    criaCartao('Botânica', 'O que é clorofila?', 'É o pigmento responsável por absorver luz para a fotossíntese.'),
    criaCartao('Botânica', 'O que é raiz?', 'É o órgão vegetal responsável por fixar a planta ao solo e absorver água e nutrientes.'),
    criaCartao('Botânica', 'O que são estômatos?', 'São estruturas na epiderme das folhas que regulam a troca de gases e a transpiração.'),
    criaCartao('Zoologia', 'O que é vertebrado?', 'É um animal que possui coluna vertebral.'),
    criaCartao('Zoologia', 'O que é invertebrado?', 'É um animal que não possui coluna vertebral.'),
    criaCartao('Zoologia', 'Quais são os principais grupos de vertebrados?', 'Peixes, anfíbios, répteis, aves e mamíferos.'),
    criaCartao('Zoologia', 'O que é homeotermia?', 'É a capacidade de manter a temperatura corporal constante, independente do ambiente.'),
    criaCartao('Zoologia', 'O que são artrópodes?', 'São invertebrados com exoesqueleto, corpo segmentado e apêndices articulados.'),
    criaCartao('Ecologia', 'O que é ecossistema?', 'É um conjunto formado pelos seres vivos e o ambiente onde vivem, interagindo entre si.'),
    criaCartao('Ecologia', 'O que é biodiversidade?', 'É a variedade de espécies de seres vivos em um determinado ambiente.'),
    criaCartao('Ecologia', 'O que é cadeia alimentar?', 'É a sequência de transferência de energia e nutrientes entre os seres vivos.'),
    criaCartao('Ecologia', 'O que é nicho ecológico?', 'É o papel que uma espécie desempenha em um ecossistema.'),
    criaCartao('Ecologia', 'O que é bioma?', 'É um grande conjunto de ecossistemas com características semelhantes.'),
    criaCartao('Fisiologia', 'O que é homeostase?', 'É a capacidade do organismo de manter o equilíbrio interno.'),
    criaCartao('Fisiologia', 'O que são hormônios?', 'São substâncias químicas produzidas pelas glândulas endócrinas que regulam funções do corpo.'),
    criaCartao('Fisiologia', 'Qual é a função do sistema respiratório?', 'Fornecer oxigênio ao corpo e eliminar dióxido de carbono.'),
    criaCartao('Fisiologia', 'O que é o sistema circulatório?', 'É o sistema responsável pelo transporte de sangue, nutrientes, gases e resíduos pelo corpo.'),
    criaCartao('Fisiologia', 'Qual é a função dos rins?', 'Filtrar o sangue e produzir urina para eliminar resíduos do corpo.'),
    criaCartao('Microbiologia', 'O que são bactérias?', 'São microrganismos unicelulares procariontes.'),
    criaCartao('Microbiologia', 'O que são vírus?', 'São partículas infecciosas que dependem de células hospedeiras para se replicar.'),
    criaCartao('Microbiologia', 'O que é fungo?', 'É um organismo eucarionte que pode ser unicelular ou multicelular.'),
    criaCartao('Microbiologia', 'O que é protozoário?', 'É um organismo unicelular eucarionte encontrado em ambientes aquáticos ou no solo.'),
    criaCartao('Microbiologia', 'O que é microbiota?', 'É o conjunto de microrganismos que habitam um organismo, como a microbiota intestinal.'),
    criaCartao('Evolução', 'O que é seleção natural?', 'É o processo pelo qual organismos mais adaptados têm maior chance de sobreviver e se reproduzir.'),
    criaCartao('Evolução', 'Quem foi Charles Darwin?', 'Foi o naturalista que propôs a teoria da evolução por seleção natural.'),
    criaCartao('Evolução', 'O que são fósseis?', 'São restos ou vestígios de organismos preservados em rochas.'),
    criaCartao('Evolução', 'O que é adaptação?', 'É uma característica que aumenta as chances de sobrevivência e reprodução de um organismo.'),
    criaCartao('Evolução', 'O que é especiação?', 'É o processo pelo qual novas espécies se formam a partir de populações ancestrais.'),
    criaCartao('Anatomia', 'Quantos ossos tem o corpo humano?', 'O corpo humano adulto possui 206 ossos.'),
    criaCartao('Anatomia', 'Qual é a função do sistema nervoso?', 'Controlar e coordenar as funções do corpo e responder aos estímulos do ambiente.'),
    criaCartao('Anatomia', 'O que é o coração?', 'É o órgão responsável por bombear o sangue pelo corpo.'),
    criaCartao('Anatomia', 'O que são músculos?', 'São tecidos que permitem o movimento do corpo.'),
    criaCartao('Anatomia', 'Qual é a função dos pulmões?', 'Realizar as trocas gasosas entre o sangue e o ar.');




